### ISSUE TITLE
Il manque la case pour activer les repousses

### ISSUE THREAD

**Issue by PakitoEu** [AngefloSH/PokemonEncCalc#1]
Sur la dernière version - 5.9.1 - il manque la case qui permet d'activer un repousse et de rendre le niveau du repousseur sélectionnable.

Du coup, aucune possibilité de voir ce que l'on peut faire via ce type de recherche.

Merci d'avance pour la correction ;)

**Comment by PakitoEu** [comment]
Apparemment le problème est résolu. Cela c'est produit pour moi et certains de mes viewers, et ça a disparu comme c'était venu, en même temps. Mystère et boule de gomme.

**Comment by AngefloSH** [comment]
Corrigé pour la prochaine version. Merci pour le retour.
